# Generated by Django 5.2.4 on 2025-12-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AppOneSDG", "0003_alter_reservation_reservationdate"),
    ]

    operations = [
       
        migrations.AddField(
            model_name="reservation",
            name="quantityBorrowed",
            field=models.IntegerField(default=0, verbose_name="Quantity borrowed"),
        ),
    ]
