# Generated by Django 5.2.4 on 2025-12-27 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AppOneSDG", "0004_remove_reservation_equipquantity_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipmentReturn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantityReturned", models.IntegerField()),
                ("dateReturned", models.DateField()),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "equipId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppOneSDG.equipment",
                    ),
                ),
                (
                    "userId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
