# Generated by Django 5.2.4 on 2025-12-31 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AppOneSDG", "0005_equipmentreturn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="equipLocation",
            field=models.CharField(
                choices=[
                    ("Available", "Available"),
                    ("Borrowed", "Borrowed"),
                    ("Lost", "Lost"),
                    ("Written Off", "Written Off"),
                ],
                default="Available",
                max_length=100,
                verbose_name="Location of equipment",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reservationStatus",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Overdue", "Overdue"),
                    ("Critical Overdue", "Critical Overdue"),
                    ("Active", "Active"),
                    ("Complete", "Complete"),
                    ("Written Off", "Written Off"),
                ],
                default="Active",
                max_length=100,
                verbose_name="Status of reservation",
            ),
        ),
    ]
