# Generated by Django 5.2.4 on 2026-01-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AppOneSDG", "0006_alter_equipment_equiplocation_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="adminUserId",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="reservationId",
        ),
        migrations.AddField(
            model_name="equipment",
            name="low_stock_threshold",
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="equipLocation",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Location of equipment"
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="equipStatus",
            field=models.CharField(
                default="Available", max_length=100, verbose_name="Status of equipment"
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="equipType",
            field=models.CharField(
                choices=[
                    ("PC Peripherals", "PC Peripherals"),
                    ("Non Portable PC", "Non Portable PC"),
                    ("Laptop", "Laptop"),
                    ("Mobile Device", "Mobile Device"),
                    ("VR Headset", "VR Headset"),
                    ("VR Controller", "VR Controller"),
                    ("Camera/Sensors", "Camera/Sensors"),
                    ("Furniture", "Furniture"),
                    ("Presentation Tools", "Presentation Tools"),
                    ("Stationary", "Stationary"),
                    ("Furniture", "Furniture"),
                    ("Accessories", "Accessories"),
                    ("Other", "Other"),
                ],
                max_length=100,
                verbose_name="Equipment type",
            ),
        ),
        migrations.DeleteModel(
            name="Alert",
        ),
        migrations.DeleteModel(
            name="Booking",
        ),
    ]
